### ISSUE TITLE
On ethr-did internal versions, interaction with demo.uport.space does not save attestations

### ISSUE THREAD

**Issue by mirceanis** [uport-project/uport-mobile-issues#35]
## Current Behavior
Logging in to demo.uport.space does not show the demo app in contacts.
Can't see any attestations or contacts either.

## Expected Behavior
User should see attestations & contacts

### Steps to Reproduce

* install a recent version with ethr-did (ex v355)
* try to use demo.uport.space
* user should see attestations from the demoapp but nothing appears, neither do contacts.

### Environment Details

* App Version: v355 (any recent version with ethr-did, definitely > v338)
* Mobile OS Version: Android (but not necessarily Android specific)

**Comment by pelle** [comment]
@mirceanis @Eseoghene  I removed apps from the contact lists recently, since we now have real contacts. We need to find a replacement for them in the future

**Comment by mirceanis** [comment]
This is about attestations/verifications too.

Follow this scenario:
* using a recent build (ex v355)
* go to demo.uport.space on mobile browser and log in. (can't use desktop browser because of push messaging issue)
* tap next and then issue a verification
* uPort pops up to accept the verification. After accept, user is returned to the browser
* now, open uPort app and look for that verification
* no verifications appear in the Verifications tab

**Comment by zachferland** [comment]
Changed title to reflect attestation issue

**Comment by zachferland** [comment]
demo.uoprt.space runs the minor release of the libs, I think this issue reflects where we will have to make one small breaking code change in the upgrade path for developers, unless I am missing something about expect account/type behavior for this release. This issue was mentioned on last minor release as well, but this is good confirmation/example of it. 

This issue is caused by issuing attestations to the account address/mind rather than the primary did, i.e.
```
{ address: "2oykfw2mQCsX5kxKiLiimMVjxSPu8Mgx269",
did:"did:ethr:0x36bd2765cdef42e5cffeb7a48da470fce1877985",
name:"uPort User",
networkAddress:"2oykfw2mQCsX5kxKiLiimMVjxSPu8Mgx269",
publicEncKey:"rNtQH1tot8Otw4yGDdf+fjVfd0WYX0aBCwiHtEv6zSc=" }
```
Given this response, attestations are issued to the address. This has been the default use were devs where using the address field for both contract call, on chain lookups and issuing attestations. This is also not just a did issue, but something we should have added for account type selection as well.

Seem like we want attestation created for dids to be issued to their did not an account with mnid, unless we don't care and will store them all, although still would be confusing for people consuming them. 

A possible suggested upgrade path, is tell devs to keep using the address field for contract call, on chain looks ups, but now issue any attestations to res.did instead of res.address

New app with minor released lib will place did in res.did while address will include mnid of account. Current app with minor release lib will place mnid or same val in both res.did and res.address, so that those attestations are still issued in the same way, while did identities will also have attestations issued correctly.

**Comment by pelle** [comment]
@aldigjo when showing attetations in the selector, check for both where sub === MNID and did:uport:MNID

**Comment by aldigjo** [comment]
I haven't been able to recreate this issue. Are we talking about fresh identities based on the internal release? As far as I can tell the "address" in the credentials object is the full did

**Comment by pelle** [comment]
@zachferland did you say you fixed this? I don't see a PR in code review?

**Comment by Eseoghene** [comment]
2

**Comment by zachferland** [comment]
@pelle @aldigjo two different things here, the creation of the issue in the demo used to be because res.address was used as the subject before we decide on change in minor release libs (so credentials was issued to account not main did), with both lib changes and demo changes, its not issued to primary did, so you won't see this issue

the fix mentioned by pelle is something else that seems like a valid condition to support in mobile, although it should almost never happen
